# Generated by Django 4.1.4 on 2022-12-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='Card yazısı')),
                ('image', models.FileField(upload_to=None, verbose_name='Card Resim')),
                ('date_now', models.DateTimeField(verbose_name='Paylaşım Zamanı')),
            ],
        ),
    ]
