# Generated by Django 4.1.4 on 2022-12-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_card_user_alter_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategori Adı')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım Zamanı'),
        ),
    ]
