# Generated by Django 4.1.4 on 2022-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priece',
            field=models.IntegerField(null=True, verbose_name='Fiyat'),
        ),
    ]
