# Generated by Django 4.1.4 on 2022-12-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.card', verbose_name='Kart'),
        ),
    ]
